radarr:
  image:
    repository: linuxserver/radarr
    pullPolicy: IfNotPresent
    tag: version-3.0.1.4259
  env:
    TZ: America/Achorage
    PUID: "1100"
    PGID: "1100"
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.middlewares: "traefik-local-ipwhitelist@kubernetescrd"
  persistence:
    config:
      enabled: true
  #podAnnotations:
  #  backup.velero.io/backup-volumes: config
