bitwardenrs:
  image:
    repository: bitwardenrs/server
    tag: "1.21.0"
  fullnameOverride: "bitwarden"
  bitwardenrs:
    signupsAllowed: true
    admin:
      enabled: false
  persistence:
    enabled: true
    size: 954Mi
  podAnnotations:
    backup.velero.io/backup-volumes: bitwarden
  extraEnvVars:
    TZ: America/Anchorage
templates:
  backup_schedule: ""
