bitwardenrs:
  fullnameOverride: "bitwarden"
  bitwardenrs:
    signupsAllowed: true
    admin:
      enabled: false
  persistence:
    enabled: true
    size: 954Mi
  podAnnotations:
    backup.velero.io/backup-volumes: bitwarden
templates:
  backup_schedule: ""
