pihole:
    # Default values for pihole.
    # This is a YAML-formatted file.
    # Declare variables to be passed into your templates.
    image:
      tag: v5.6

    doh:
      # set to true to enabled dns over https via cloudflared
      repository: "registry.glacier.dev/cdk/cloudflared"
      tag: latest
    serviceDns:
      loadBalancerIP: "192.168.24.23"

    serviceWeb:
      loadBalancerIP: "192.168.24.23"
    virtualHost: pihole.in.lab

    ingress:
      hosts:
        # virtualHost (default value is pi.hole) will be appended to the hosts
        - pihole.in.lab

    # Use an existing secret for the admin password.
    admin:
      existingSecret: "pihole-admin"
      passwordKey: "password"


      customDnsEntries: []
      # Here you can add custom dns entries to override the
      # dns resolution with. All lines will be added to the
      # pihole dnsmasq configuration.
      # The format should be like:
      # - address=/foo.bar/192.168.178.10
      # - address=/bar.foo/192.168.178.11

      additionalHostsEntries: []
      # Dnsmasq reads the /etc/hosts file to resolve ips. You can add additional entries if you like
      # - 192.168.0.3     host4
      # - 192.168.0.4     host5

    adlists: {}
      # If you want to provide blocklists, add them here.
      # - https://hosts-file.net/grm.txt
      # - https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts

    blacklist: {}
      # If you want to have special domains blacklisted, add them here
      # - *.blackist.com

    regex: {}
      # Add regular expression blacklist items
      # - (^|\.)facebook\.com$
templates:
    secrets: "lab"
