traefik:
  image:
    name: traefik
    tag: "2.4"

  globalArguments:
    - "--global.checknewversion"
    - "--serversTransport.insecureSkipVerify=true"
  service:
    spec:
      externalTrafficPolicy: Local
  # Create an IngressRoute for the dashboard
  ingressRoute:
    dashboard:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: "traefik-local-ipwhitelist@kubernetescrd"

  providers:
    kubernetesIngress:
      enabled: true
      publishedService:
        enabled: true
templates:
    install_cert: false
    http_redirect:
      enable: false
