templates:
    install_cert: false
    http_redirect:
        enable: true

traefik:

  globalArguments:
    - "--global.checknewversion"
    - "--serversTransport.insecureSkipVerify=true"
  service:
    spec:
      externalTrafficPolicy: Local
  # Create an IngressRoute for the dashboard
  ingressRoute:
    dashboard:
      enabled: false

  providers:
    kubernetesIngress:
      enabled: true
      publishedService:
        enabled: true
