traefik:
  service:
    spec:
      externalTrafficPolicy: Local
      loadBalancerIP: "192.168.24.24"
templates:
    dashboard_hostname: "traefik.in.lab"
    #dashboard_auth: "lab"
    #default_cert: "traefik-cert"
