nextcloud:
  ## Nextcloud specific configuration
  settings:

    ## Nextcloud administrative user
    admin:
      ## Administrative user name
      name: Admin

    ## Password for administrative user (default: a 10 char. alpahnumerical random password will be generated)
    password: password
