nextcloud:
  image:
    tag: "20.0.7-apache"

  ingress:
    enabled: true
    maxBodySize: 64m
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.middlewares: "traefik-local-ipwhitelist@kubernetescrd"

    ## Hosts
    hosts:
      - host: nextcloud.in.lab

  env:
    TZ: America/Anchorage


  ## Nextcloud specific configuration
  settings:

    ## Nextcloud administrative user
    admin:
      ## Administrative user name
      name: Admin

    ## Password for administrative user (default: a 10 char. alpahnumerical random password will be generated)
      password: changeme

    trustedDomains: "nextcloud.in.lab"

  ## Storage parameters
  storage:
    ## Nextcloud storage (all Nextcloud internal files, plugins, extensions etc.)
    nextcloud:
      ## Set persistentVolumenClaimName to reference an existing PVC
      persistentVolumeClaimName:

      ## Alternative set requestedSize to define a size for a dynmaically created PVC
      requestedSize: 1Gi

      ## the storage class name
      className: nfs-client

      ## Default access mode (ReadWriteOnce)
      accessModes:
        - ReadWriteOnce

    ## Nextcloud user data storage
    nextcloudData:
      ## Set persistentVolumenClaimName to reference an existing PVC
      persistentVolumeClaimName:

      ## Alternative set requestedSize to define a size for a dynmaically created PVC
      requestedSize: 10Gi

      ## the storage class name
      className: nfs-client

      ## Default access mode (ReadWriteOnce)
      accessModes:
        - ReadWriteOnce
