name: sealed-secretes
apiVersion: v2
version: 1.0.0
dependencies:
    - name: sealed-secrets
      version: '~1.14.1-r1'
      #repository: "@stable"
      repository: https://bitnami-labs.github.io/sealed-secrets
