jellyfin:
  image:
    repository: linuxserver/jellyfin
    tag: version-10.6.4-1
  env:
    TZ: America/Anchorage
    PUID: "1100"
    PGID: "1100"
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: "traefik-local-ipwhitelist@kubernetescrd"
  persistence:
    config:
      enabled: true
  #podAnnotations:
  #  backup.velero.io/backup-volumes: config
