apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-admin
  namespace: pihole
spec:
  encryptedData:
    password: AgBaOjyJtqt4R71z53EGjAFdSFF5X+O0NxrApHn3/fIqwnFN3ln0y1tSFuGzTJ4F5IXQpP5DN+OgTAzNW5A6ThISeW3A8/kZhQSv60V33v97MXXzjgOv+i0XIqMWn01IuMBLjBEw1vijc6AZ/nfJMB5BMbb85o6QXyaMk9/SNDeb9WqYDEPhUL2PJvlyN7P7YHHHlwOnnmb/xR9vJUssnooM5rmS2Jxm3gcXjEbPrbZTnZo9/azQrhHI9LahoQ0uO4ZNU+VNzGGEI3GS7pQqXRGEFdCVMdLcrmOKVJaT6+OB1lrSXnsluYu9uLJwMmYPWTTA1pe3IZIzSnYwUL3pxQjcUqoL8ijXujYo2LiS5z+0a7CAsoMtF65/scV3HcVkpwzYs/BoZoqDBB2w5E4HS6kj2Gk7YT5EMBIzl+yWdeg0LiB1r5HXloa0wycE5vRk1ozzQjVESycalQJYFKdNdoOiuISR1MVvrCxg0DtVkqEJSzg+0Ixb2PUX8YCdDN3h7DZbrO+vkGEhqzmRZC9Hicd1sSMYD2O9SWYMCgNIXIYZGYIz6T/gnnZmS7MB3kcMWhWf8hDZ6s1RZfjs0baCQWG9RFKm2COJg3uy/e2WtTnG8cHJIiI5xr4MO9VZHQD8457oAg6NNrN6e2cSKnKhQuwRU6G4gmy/FySePl+di8MzpLvoorhrHKqSfgdzKxS5N3ZgqfayM3el6bIHQA==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-admin
      namespace: pihole

