argo-cd:
  installCRDs: false
  global:
    image:
      tag: v1.8.4
  server:
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: "traefik-local-ipwhitelist@kubernetescrd"
templates: {}
