metallb:
  existingConfigMap: metallb-config
  prometheus:
    enabled: true
    serviceMonitor:
      # enable support for Prometheus Operator
      enabled: false
  controller:
    image:
      registry: docker.io
      repository: bitnami/metallb-controller
      tag: 0.9.6-debian-10-r32
  speaker:
    image:
      registry: docker.io
      repository: bitnami/metallb-speaker
      tag: 0.9.6-debian-10-r31
