sabnzbd:
  image:
    repository: linuxserver/sabnzbd
    tag: version-3.1.1
  env:
    timezone: America/Anchorage
    puid: "1100"
    pgid: "1100"
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: "traefik-local-ipwhitelist@kubernetescrd"
  persistence:
    config:
      enabled: true
  #podAnnotations:
  #  backup.velero.io/backup-volumes: config
